{{- if (index .Values.global "common-config" "enabled") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: subride
  labels:
    {{- include "main-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: common-config
data:
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}